"""New Migration

Revision ID: 223b4b4da68e
Revises: 
Create Date: 2022-09-25 17:50:52.074396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223b4b4da68e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sociedad',
    sa.Column('id_sociedad', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_sociedad')
    )
    op.create_table('ubicacion',
    sa.Column('id_ubicacion', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_ubicacion')
    )
    op.create_table('empleado',
    sa.Column('num_emp', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sociedad_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sociedad_id'], ['sociedad.id_sociedad'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicacion.id_ubicacion'], ),
    sa.PrimaryKeyConstraint('num_emp')
    )
    op.create_table('data_personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('cuenta', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('num_emp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['num_emp'], ['empleado.num_emp'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_personal')
    op.drop_table('empleado')
    op.drop_table('ubicacion')
    op.drop_table('sociedad')
    # ### end Alembic commands ###
